database:
  type: yaml # mysql, sqlite, yaml
  mysql:
    host: localhost
    port: 3306
    database: mmleader
    user: root
    password: password
    pool-size: 5

options:
  max-kills-per-mob: 100
  async-threads: 1

party:
  provider: auto # auto, none, parties, mmocore, mythicdungeons

whitelist:
  enabled: false
  mobs:
    - example_mob_1
    - example_mob_2
