database:
  type: sqlite
  mysql:
    host: localhost
    port: 3306
    database: mmleader
    user: root
    password: password

options:
  sort-mode: asc
  debug: false

party:
  provider: auto
  # auto, parties, mmocore, mythicdungeons, none

whitelist:
  enabled: true
  mobs:
    - zombie_king