# Database

database:
  # mysql sqlite yaml
  type: yaml

  mysql:
    host: localhost
    port: 3306
    database: mmleader
    user: root
    password: password
    pool-size: 10

# Whitelist

whitelist:
  enabled: true
  mobs:
    - example_boss

# Party System

party:
  # auto none parties mmocore mythicdungeons
  provider: auto
